// vue_laravel/Laravel-Inertia-Vue-2024/resources/js/Pages/Apps/Transactions/Index.vue
<template>
    <Head>
        <title>Transactions - Point Of Sale</title>
    </Head>
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card border-0 rounded-3 shadow">
                            <div class="card-body">
                                <div class="input-group mb-3">
                                    <span class="input-group-text"
                                        ><i class="fa fa-barcode"></i
                                    ></span>
                                    <input
                                        type="text"
                                        class="form-control"
                                        v-model="barcode"
                                        @keyup="searchProduct"
                                        placeholder="Scan or Input Barcode"
                                    />
                                </div>
                                <div class="mb-3">
                                    <label class="form-label fw-bold"
                                        >Product Name</label
                                    >
                                    <input
                                        type="text"
                                        class="form-control"
                                        :value="product.title"
                                        placeholder="Product Name"
                                        readonly
                                    />
                                </div>
                                <div class="mb-3">
                                    <label class="form-label fw-bold"
                                        >price</label
                                    >
                                    <input
                                        type="number"
                                        class="form-control"
                                        :value="formatPrice(harga)"
                                        placeholder="Rp 0"
                                        min="0"
                                        readonly
                                    />
                                </div>
                                <div class="mb-3">
                                    <label class="form-label fw-bold"
                                        >Qty</label
                                    >
                                    <input
                                        type="number"
                                        class="form-control text-center"
                                        v-model="qty"
                                        placeholder="Qty"
                                        min="1"
                                    />
                                </div>
                                <div class="text-end">
                                    <button
                                        @click.prevent="clearSearch"
                                        class="btn btn-warning btn-md border-0 shadow text-uppercase mt-3 me-2"
                                        :disabled="!product.id"
                                    >
                                        CLEAR
                                    </button>
                                    <button
                                        @click.prevent="addToCart"
                                        class="btn btn-success btn-md border-0 shadow text-uppercase mt-3"
                                        :disabled="!product.id"
                                    >
                                        ADD ITEM
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div v-if="session.error" class="alert alert-danger">
                            {{ session.error }}
                        </div>

                        <div v-if="session.success" class="alert alert-success">
                            {{ session.success }}
                        </div>

                        <div
                            class="card border-0 rounded-3 shadow border-top-success"
                        >
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4 col-4">
                                        <h4 class="fw-bold">GRAND TOTAL</h4>
                                    </div>
                                    <div class="col-md-8 col-8 text-end">
                                        <h4 class="fw-bold">
                                            TK. {{ formatPrice(grandTotal) }}
                                        </h4>
                                        <div v-if="change > 0">
                                            <hr />
                                            <h5 class="text-success">
                                                Change :
                                                <strong
                                                    >Rp.
                                                    {{
                                                        formatPrice(change)
                                                    }}</strong
                                                >
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card border-0 rounded-3 shadow">
                            <div class="card-body">
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label class="fw-bold">Cashier</label>
                                        <input
                                            class="form-control"
                                            type="text"
                                            :value="auth.user.name"
                                            readonly
                                        />
                                    </div>
                                    <div class="col-md-6 float-end">
                                        <label class="fw-bold">Customer</label>
                                        <VueMultiselect
                                            v-model="customer_id"
                                            label="name"
                                            track-by="name"
                                            :options="customers"
                                        ></VueMultiselect>
                                    </div>
                                </div>
                                <hr />
                                <table class="table table-bordered">
                                    <thead>
                                        <tr style="background-color: #e6e6e7">
                                            <th scope="col">#</th>
                                            <th scope="col">Product Name</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Qty</th>
                                            <th scope="col">Sub Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr
                                            v-for="cart in carts"
                                            :key="cart.id"
                                        >
                                            <td class="text-center">
                                                <button
                                                    @click.prevent="
                                                        destroyCart(cart.id)
                                                    "
                                                    class="btn btn-danger btn-sm rounded-pill"
                                                >
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </td>
                                            <td>{{ cart.product.title }}</td>
                                            <td>
                                                TK.
                                                {{
                                                    formatPrice(
                                                        cart.product.sell_price
                                                    )
                                                }}
                                            </td>
                                            <td class="text-center">
                                                {{ cart.qty }}
                                            </td>
                                            <td class="text-end">
                                                TK.
                                                {{ formatPrice(cart.price) }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td
                                                colspan="4"
                                                class="text-end fw-bold"
                                                style="
                                                    background-color: #e6e6e7;
                                                "
                                            >
                                                TOTAL
                                            </td>
                                            <td
                                                class="text-end fw-bold"
                                                style="
                                                    background-color: #e6e6e7;
                                                "
                                            >
                                                TK.
                                                {{ formatPrice(carts_total) }}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <hr />
                                <div
                                    class="d-flex align-items-end flex-column bd-highlight mb-3"
                                >
                                    <div class="mt-auto bd-highlight">
                                        <label>Discount (TK.)</label>
                                        <input
                                            type="number"
                                            v-model="discount"
                                            @keyup="setDiscount"
                                            class="form-control"
                                            placeholder="Discount (Rp.)"
                                        />
                                    </div>
                                    <div class="bd-highlight mt-4">
                                        <label>Pay (TK.)</label>
                                        <input
                                            type="number"
                                            v-model="cash"
                                            @keyup="setChange"
                                            class="form-control"
                                            placeholder="Pay (Rp.)"
                                        />
                                    </div>
                                </div>
                                <div class="text-end mt-4">
                                    <button
                                        class="btn btn-warning btn-md border-0 shadow text-uppercase me-2"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        @click.prevent="storeTransaction"
                                        class="btn btn-purple btn-md border-0 shadow text-uppercase"
                                        :disabled="
                                            cash < grandTotal || grandTotal == 0
                                        "
                                    >
                                        Pay Order & Print
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</template>

<script>
//import layout
import LayoutApp from "../../../Layouts/App.vue";

//import Heade from Inertia
import { Head } from "@inertiajs/inertia-vue3";

//import VueMultiselect
import VueMultiselect from "vue-multiselect";
import "vue-multiselect/dist/vue-multiselect.css";

//import ref form vue
import { ref } from "vue";

//import axios
import axios from "axios";

//import inerita adapter
import { Inertia } from "@inertiajs/inertia";

//import sweet alert2
import Swal from "sweetalert2";

export default {
    //layout
    layout: LayoutApp,

    //register components
    components: {
        Head,
        VueMultiselect,
    },

    //props
    props: {
        auth: Object,
        customers: Array,
        carts_total: Number,
        session: Object,
        carts: Array,
    },

    //composition API
    setup(props) {
        //define state
        const barcode = ref("");
        const product = ref({});
        const qty = ref(1);
        const harga = ref(0);
        //metho "searchProduct"
        const searchProduct = () => {
            //fetch with axios
            axios
                .post("/apps/transactions/searchProduct", {
                    //send data "barcode"
                    barcode: barcode.value,
                })
                .then((response) => {
                    if (response.data.success) {
                        //assign response to state "product"
                        product.value = response.data.data;
                        harga.value = response.data.data.sell_price;
                    } else {
                        //set state "product" to empty object
                        product.value = {};
                        harga.value = 0;
                    }
                });
        };

        //method "clearSearch"
        const clearSearch = () => {
            //set state "product" to empty object
            product.value = {};

            //set state "barcode" to empty string
            barcode.value = "";
            qty.value = 1;
            harga.value = 0;
        };

        //define state grandTotal
        const grandTotal = ref(props.carts_total);

        //method add to cart
        const addToCart = () => {
            //send data to server
            Inertia.post(
                "/apps/transactions/addToCart",
                {
                    //data
                    product_id: product.value.id,
                    qty: qty.value,
                    sell_price: product.value.sell_price,
                },
                {
                    onSuccess: () => {
                        //call method "clearSaerch"
                        clearSearch();

                        //set qty to "1"
                        qty.value = 1;

                        //update state "grandTotal"
                        grandTotal.value = props.carts_total;

                        //set cash to "0"
                        cash.value = 0;

                        //set change to "0"
                        change.value = 0;
                        harga.value = 0;
                    },
                }
            );
        };

        //method "destroyCart"
        const destroyCart = (cart_id) => {
            Inertia.post(
                "/apps/transactions/destroyCart",
                {
                    cart_id: cart_id,
                },
                {
                    onSuccess: () => {
                        //update state "grandTotal"
                        grandTotal.value = props.carts_total;

                        //set cash to "0"
                        cash.value = 0;

                        //set change to "0"
                        change.value = 0;
                    },
                }
            );
        };

        //define state "cash", "change" dan "discount"
        const cash = ref(0);
        const change = ref(0);
        const discount = ref(0);

        //method "setDiscount"
        const setDiscount = () => {
            //set grandTotal
            grandTotal.value = props.carts_total - discount.value;

            //set cash to "0"
            cash.value = 0;

            //set change to "0"
            change.value = 0;
        };

        //method "setChange"
        const setChange = () => {
            //set change
            change.value = cash.value - grandTotal.value;
        };

        //define state "customer_id"
        const customer_id = ref("");

        //method "storeTransaction"
        const storeTransaction = () => {
            //HTTP request
            axios
                .post("/apps/transactions/store", {
                    //send data to server
                    customer_id: customer_id.value ? customer_id.value.id : "",
                    discount: discount.value,
                    grand_total: grandTotal.value,
                    cash: cash.value,
                    change: change.value,
                })
                .then((response) => {
                    //call method "clearSaerch"
                    clearSearch();

                    //set qty to "1"
                    qty.value = 1;

                    //set grandTotal
                    grandTotal.value = props.carts_total;

                    //set cash to "0"
                    cash.value = 0;

                    //set change to "0"
                    change.value = 0;

                    //set customer_id to ""
                    customer_id.value = "";

                    //show success alert
                    Swal.fire({
                        title: "Success!",
                        text: "Transaction Successfully.",
                        icon: "success",
                        showConfirmButton: false,
                        timer: 2000,
                    }).then(() => {
                        setTimeout(() => {
                            //print
                            window.open(
                                `/apps/transactions/print?invoice=${response.data.data.invoice}`,
                                "_blank"
                            );

                            //reload page
                            location.reload();
                        }, 50);
                    });
                });
        };

        return {
            barcode,
            product,
            harga,
            searchProduct,
            clearSearch,
            qty,
            grandTotal,
            addToCart,
            destroyCart,
            cash,
            change,
            discount,
            setDiscount,
            setChange,
            customer_id,
            storeTransaction,
        };
    },
};
</script>

<style></style>

// project_react_laravel/point-of-sales/resources/js/Pages/Dashboard/Transactions/Index.jsx
import React, { useState, useEffect } from 'react';
import DashboardLayout from '@/Layouts/DashboardLayout';
import { Head, router, useForm, usePage } from '@inertiajs/react';
import Card from '@/Components/Dashboard/Card';
import Input from '@/Components/Dashboard/Input';
import { IconArrowRight, IconMoneybag, IconPencilPlus, IconReceipt, IconShoppingCart, IconShoppingCartPlus, IconTrash } from '@tabler/icons-react';
import Button from '@/Components/Dashboard/Button';
import axios from 'axios';
import InputSelect from '@/Components/Dashboard/InputSelect';
import Table from '@/Components/Dashboard/Table';
import toast from 'react-hot-toast';

export default function Index({ carts, carts_total, customers }) {
    const { errors, auth } = usePage().props;

    const [barcode, setBarcode] = useState('');
    const [product, setProduct] = useState({});
    const [qty, setQty] = useState(1);
    const [grandTotal, setGrandTotal] = useState(carts_total);
    const [cash, setCash] = useState(0);
    const [change, setChange] = useState(0);
    const [discount, setDiscount] = useState(0);
    const [selectedCustomer, setSelectedCustomer] = useState(null);

    // Helper function to format price
    const formatPrice = (price) => {
        return price.toLocaleString('en-BD', { style: 'currency', currency: 'BDT' });
    };

    const { data, setData, post, processing } = useForm({
        customer_id: '',
        product_id: '',
        sell_price: '',
        qty: '',
        discount: '',
        cash: '',
        change: '',
    });

    // Set selected customer
    const setSelectedCustomerHandler = (value) => {
        setSelectedCustomer(value);
        setData('customer_id', value.id);
    };

    useEffect(() => {
        setGrandTotal(carts_total - discount);
        setChange(cash - (carts_total - discount));
    }, [carts_total, discount, cash]);

    const searchProduct = (e) => {
        e.preventDefault();
        axios.post('/dashboard/transactions/searchProduct', { barcode })
            .then(response => {
                if (response.data.success) {
                    setProduct(response.data.data);
                } else {
                    setProduct({});
                }
            });
    };

    const addToCart = (e) => {
        e.preventDefault();
        router.post(route('transactions.addToCart'), {
            product_id: product.id,
            sell_price: product.sell_price,
            qty,
        });
    };

    const storeTransaction = (e) => {
        e.preventDefault();
        if (!data.customer_id) {
            toast('Please select a customer first', {
                style: {
                    borderRadius: '10px',
                    background: '#FF0000',
                    color: '#fff',
                },
            });
        } else {
            if (cash >= grandTotal) {
                router.post(route('transactions.store'), {
                    customer_id: selectedCustomer ? selectedCustomer.id : '',
                    discount,
                    grand_total: grandTotal,
                    cash,
                    change,
                }, {
                    onSuccess: () => {
                        toast('Transaction data saved successfully', {
                            icon: '👏',
                            style: {
                                borderRadius: '10px',
                                background: '#1C1F29',
                                color: '#fff',
                            },
                        })
                    }
                });
            }
        }
    };

    return (
        <>
            <Head title="Transaction Dashboard" />
            <div className="grid grid-cols-12 gap-4">
                <div className="col-span-12 md:col-span-4">
                    <Card
                        title={'Add Product Data'}
                        icon={<IconShoppingCart size={20} strokeWidth={1.5} />}
                        footer={
                            <Button
                                type={'submit'}
                                label={'Submit'}
                                icon={<IconShoppingCartPlus size={20} strokeWidth={1.5} />}
                                disabled={!product.id}

                                className={`border bg-white text-gray-700 hover:bg-gray-100 dark:bg-gray-950 dark:border-gray-800 dark:text-gray-200 dark:hover:bg-gray-900 mt-5 ${!product.id ? 'opacity-50 cursor-not-allowed' : ''}`}
                            />
                        }
                        form={addToCart}
                    >
                        <div className="mb-2">
                            <Input
                                type={'text'}
                                label={'Scan/Input Product Barcodev'}
                                placeholder={'Product Barcode'}
                                onChange={e => setBarcode(e.target.value)}
                                onKeyUp={searchProduct}
                            />
                        </div>
                        <div className="mb-2">
                            <Input
                                type={'text'}
                                label={'Product'}
                                placeholder={'product name'}
                                disabled
                                value={product.title || ''}
                            />
                        </div>
                        <div className="mb-2">
                            <Input
                                type={'number'}
                                label={'Quantity'}
                                placeholder={'Quantity'}
                                onChange={e => setQty(e.target.value)}
                            />
                            <small className="text-gray-500">
                                Stock : {product.stock || 0}
                            </small>
                        </div>
                    </Card>
                </div>
                <div className="col-span-12 md:col-span-8">
                    <Card
                        title={'Transaction'}
                        icon={<IconPencilPlus size={20} strokeWidth={1.5} />}
                    >
                        <div className="grid grid-cols-12 gap-4">
                            <div className="col-span-12">
                                <div className="flex justify-between">
                                    <h1 className="text-lg md:text-2xl text-black dark:text-white">Total Bill</h1>
                                    <h1 className="text-lg md:text-2xl text-black dark:text-white">
                                        {formatPrice(carts_total)}
                                    </h1>
                                </div>
                            </div>
                            <div className="col-span-12 md:col-span-6">
                                <Input
                                    type={'text'}
                                    label={'Cashier'}
                                    placeholder={'Cashier'}
                                    disabled
                                    value={auth.user.name}
                                />
                            </div>
                            <div className="col-span-12 md:col-span-6">
                                <InputSelect
                                    label="Customer"
                                    data={customers}
                                    selected={selectedCustomer}
                                    setSelected={setSelectedCustomerHandler}
                                    placeholder="Customer"
                                    errors={errors.customer_id}
                                    multiple={false}
                                    searchable={true}
                                    displayKey='name'
                                />
                            </div>
                        </div>
                    </Card>

                    <Table.Card title={'Cart'} className={'mt-5'}>
                        <Table>
                            <Table.Thead>
                                <tr>
                                    <Table.Th className='w-10'>No</Table.Th>
                                    <Table.Th>Product</Table.Th>
                                    <Table.Th>Price</Table.Th>
                                    <Table.Th>Qty</Table.Th>
                                    <Table.Th>Sub Total</Table.Th>
                                    <Table.Th></Table.Th>
                                </tr>
                            </Table.Thead>
                            <Table.Tbody>
                                {carts.map((item, index) => (
                                    <tr key={item.id}>
                                        <Table.Td className='w-10'>{index + 1}</Table.Td>
                                        <Table.Td>{item.product.title}</Table.Td>
                                        <Table.Td>{formatPrice(item.price)}</Table.Td>
                                        <Table.Td>{item.qty}</Table.Td>
                                        <Table.Td>{formatPrice(item.price * item.qty)}</Table.Td>
                                        <Table.Td>
                                            <Button
                                                type={'delete'}
                                                icon={<IconTrash size={16} strokeWidth={1.5} />}
                                                className={'border bg-rose-100 border-rose-300 text-rose-500 hover:bg-rose-200 dark:bg-rose-950 dark:border-rose-800 dark:text-gray-300  dark:hover:bg-rose-900'}
                                                url={route('transactions.destroyCart', item.id)}
                                            />
                                        </Table.Td>
                                    </tr>
                                ))}
                            </Table.Tbody>
                            <tfoot>
                                <tr>
                                    <Table.Td></Table.Td>
                                    <Table.Td></Table.Td>
                                    <Table.Td></Table.Td>
                                    <Table.Td>Total</Table.Td>
                                    <Table.Td>{formatPrice(carts_total)}</Table.Td>
                                    <Table.Td></Table.Td>
                                </tr>
                            </tfoot>
                        </Table>
                    </Table.Card>

                    <div className="my-5"></div>

                    <Card
                        title={'Payment'}
                        icon={<IconReceipt size={20} strokeWidth={1.5} />}
                    >
                        <div className="grid grid-cols-12 gap-4">
                            <div className="col-span-12 md:col-span-6">
                                <Input
                                    type={'number'}
                                    label={'Discount'}
                                    placeholder="Discount (BDT.)"
                                    onChange={e => setDiscount(parseInt(e.target.value) || 0)}
                                />
                            </div>
                            <div className="col-span-12 md:col-span-6">
                                <Input
                                    type={'number'}
                                    label={'Pay'}
                                    placeholder="Pay (BDT.)"
                                    onChange={e => setCash(parseInt(e.target.value) || 0)}
                                />
                            </div>
                        </div>
                        <Button
                            type={'submit'}
                            label={'Pay'}
                            icon={<IconMoneybag size={20} strokeWidth={1.5} />}
                            onClick={storeTransaction}
                            disabled={cash < grandTotal}
                            className={`border bg-white text-gray-700 hover:bg-gray-100 dark:bg-gray-950 dark:border-gray-800 dark:text-gray-200 dark:hover:bg-gray-900 mt-5 ${cash < grandTotal ? 'opacity-50 cursor-not-allowed' : ''}`}
                        >
                            Pay
                        </Button>
                    </Card>
                </div>
            </div >
        </>
    );
}

Index.layout = page => <DashboardLayout children={page} />;
